/**
 * @license
 * Lo-Dash 1.2.0 (Custom Build) lodash.com/license
 * Build: `lodash include="each,filter,map,extend"`
 * Underscore.js 1.4.4 underscorejs.org/LICENSE
 */
;(function(e){function t(){}function n(){for(var e,n={g:v,b:"k(m)",c:"",e:"m",f:"",h:"",i:!0,j:!!T},r=0;e=arguments[r];r++)for(var i in e)n[i]=e[i];if(e=n.a,n.d=/^[^,]+/.exec(e)[0],r="var i,m="+n.d+",u="+n.e+";if(!m)return u;"+n.h+";",n.b?(r+="var n=m.length;i=-1;if("+n.b+"){",N.unindexedChars&&(r+="if(l(m)){m=m.split('')}"),r+="while(++i<n){"+n.f+"}}else{"):N.nonEnumArgs&&(r+="var n=m.length;i=-1;if(n&&j(m)){while(++i<n){i+='';"+n.f+"}}else{"),N.enumPrototypes&&(r+="var v=typeof m=='function';"),n.i&&n.j)r+="var s=-1,t=r[typeof m]?o(m):[],n=t.length;while(++s<n){i=t[s];",N.enumPrototypes&&(r+="if(!(v&&i=='prototype')){"),r+=n.f,N.enumPrototypes&&(r+="}"),r+="}";
else if(r+="for(i in m){",(N.enumPrototypes||n.i)&&(r+="if(",N.enumPrototypes&&(r+="!(v&&i=='prototype')"),N.enumPrototypes&&n.i&&(r+="&&"),n.i&&(r+="h.call(m,i)"),r+="){"),r+=n.f+";",(N.enumPrototypes||n.i)&&(r+="}"),r+="}",N.nonEnumShadows)for(r+="var f=m.constructor;",i=0;7>i;i++)r+="i='"+n.g[i]+"';if(","constructor"==n.g[i]&&(r+="!(f&&f.prototype===m)&&"),r+="h.call(m,i)){"+n.f+"}";return(n.b||N.nonEnumArgs)&&(r+="}"),r+=n.c+";return u",Function("h,j,k,l,o,p,r","return function("+e+"){"+r+"}")(S,o,u,c,T,t,P)
}function r(e){return typeof e.toString!="function"&&typeof(e+"")=="string"}function o(e){return F.call(e)==j}function u(e){return N.argsObject&&e instanceof Array||(I?I(e):F.call(e)==O)}function i(e,n,u,a,c,l){var s=u===h;if(typeof u=="function"&&!s){u=t.createCallback(u,a,2);var p=u(e,n);if(typeof p!="undefined")return!!p}if(e===n)return 0!==e||1/e==1/n;var m=typeof e,d=typeof n;if(e===e&&(!e||"function"!=m&&"object"!=m)&&(!n||"function"!=d&&"object"!=d))return y;if(null==e||null==n)return e===n;
if(d=F.call(e),m=F.call(n),d==j&&(d=E),m==j&&(m=E),d!=m)return y;switch(d){case _:case x:return+e==+n;case w:return e!=+e?n!=+n:0==e?1/e==1/n:e==+n;case A:case C:return e==n+""}if(m=d==O,!m){if(S.call(e,"__wrapped__")||S.call(n,"__wrapped__"))return i(e.__wrapped__||e,n.__wrapped__||n,u,a,c,l);if(d!=E||!N.nodeClass&&(r(e)||r(n)))return y;var d=!N.argsObject&&o(e)?Object:e.constructor,b=!N.argsObject&&o(n)?Object:n.constructor;if(d!=b&&(!f(d)||!(d instanceof d&&f(b)&&b instanceof b)))return y}for(c||(c=[]),l||(l=[]),d=c.length;d--;)if(c[d]==e)return l[d]==n;
var g=0,p=!0;if(c.push(e),l.push(n),m){if(d=e.length,g=n.length,p=g==e.length,!p&&!s)return p;for(;g--;)if(m=d,b=n[g],s)for(;m--&&!(p=i(e[m],b,u,a,c,l)););else if(!(p=i(e[g],b,u,a,c,l)))break;return p}return L(n,function(t,n,r){return S.call(r,n)?(g++,p=S.call(e,n)&&i(e[n],t,u,a,c,l)):void 0}),p&&!s&&L(e,function(e,t,n){return S.call(n,t)?p=-1<--g:void 0}),p}function f(e){return typeof e=="function"}function a(e){return e?P[typeof e]:y}function c(e){return typeof e=="string"||F.call(e)==C}function l(e,n,r){var o=[];
if(n=t.createCallback(n,r),u(e)){r=-1;for(var i=e.length;++r<i;){var f=e[r];n(f,r,e)&&o.push(f)}}else D(e,function(e,t,r){n(e,t,r)&&o.push(e)});return o}function s(e,t,n){if(t&&typeof n=="undefined"&&u(e)){n=-1;for(var r=e.length;++n<r&&t(e[n],n,e)!==y;);}else D(e,t,n);return e}function p(e,n,r){var o=-1,i=e?e.length:0,f=Array(typeof i=="number"?i:0);if(n=t.createCallback(n,r),u(e))for(;++o<i;)f[o]=n(e[o],o,e);else D(e,function(e,t,r){f[++o]=n(e,t,r)});return f}function m(e){return e}var y=!1,d=typeof exports=="object"&&exports,b=typeof module=="object"&&module&&module.exports==d&&module,g=typeof global=="object"&&global;
(g.global===g||g.window===g)&&(e=g);var h={},v="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),j="[object Arguments]",O="[object Array]",_="[object Boolean]",x="[object Date]",w="[object Number]",E="[object Object]",A="[object RegExp]",C="[object String]",P={"boolean":y,"function":!0,object:!0,number:y,string:y,undefined:y},g={},k=RegExp("^"+(g.valueOf+"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),S=g.hasOwnProperty,F=g.toString,q=k.test(q=F.bind)&&q,I=k.test(I=Array.isArray)&&I,R=k.test(R=Object.keys)&&R,g=k.test(e.attachEvent),$=q&&!/\n|true/.test(q+g),N=t.support={};
(function(){function e(){this.x=1}var t=[];e.prototype={valueOf:1};for(var n in new e)t.push(n);for(n in arguments);N.argsObject=arguments.constructor==Object&&!(arguments instanceof Array),N.argsClass=o(arguments),N.enumPrototypes=e.propertyIsEnumerable("prototype"),N.fastBind=q&&!$,N.nonEnumArgs=0!=n,N.nonEnumShadows=!/valueOf/.test(t),N.unindexedChars="xx"!="x"[0]+Object("x")[0];try{N.nodeClass=!(F.call(document)==E&&!({toString:0}+""))}catch(r){N.nodeClass=!0}})(1);var B={a:"q,w,g",h:"var a=arguments,b=0,c=typeof g=='number'?2:a.length;while(++b<c){m=a[b];if(m&&r[typeof m]){",f:"if(typeof u[i]=='undefined')u[i]=m[i]",c:"}}"},g={a:"e,d,x",h:"d=d&&typeof x=='undefined'?d:p.createCallback(d,x)",b:"typeof n=='number'",f:"if(d(m[i],i,e)===false)return u"},k={h:"if(!r[typeof m])return u;"+g.h,b:y};
N.argsClass||(o=function(e){return e?S.call(e,"callee"):y});var M=n({a:"q",e:"[]",h:"if(!(r[typeof q]))return u",f:"u.push(i)",b:y}),T=R?function(e){return a(e)?N.enumPrototypes&&typeof e=="function"||N.nonEnumArgs&&e.length&&o(e)?M(e):R(e):[]}:M,D=n(g),B=n(B,{h:B.h.replace(";",";if(c>3&&typeof a[c-2]=='function'){var d=p.createCallback(a[--c-1],a[c--],2);}else if(c>2&&typeof a[c-1]=='function'){d=a[--c];}"),f:"u[i]=d?d(u[i],m[i]):m[i]"}),L=n(g,k,{i:y}),g=n(g,k);f(/x/)&&(f=function(e){return e instanceof Function||"[object Function]"==F.call(e)
}),t.assign=B,t.createCallback=function(e,t,n){if(null==e)return m;var r=typeof e;if("function"!=r){if("object"!=r)return function(t){return t[e]};var o=T(e);return function(t){for(var n=o.length,r=y;n--&&(r=i(t[o[n]],e[o[n]],h)););return r}}return typeof t!="undefined"?1===n?function(n){return e.call(t,n)}:2===n?function(n,r){return e.call(t,n,r)}:4===n?function(n,r,o,u){return e.call(t,n,r,o,u)}:function(n,r,o){return e.call(t,n,r,o)}:e},t.filter=l,t.forEach=s,t.forIn=L,t.forOwn=g,t.keys=T,t.map=p,t.collect=p,t.each=s,t.extend=B,t.select=l,t.identity=m,t.isArguments=o,t.isArray=u,t.isEqual=i,t.isFunction=f,t.isObject=a,t.isString=c,t.VERSION="1.2.0",typeof define=="function"&&typeof define.amd=="object"&&define.amd?(e._=t,define(function(){return t
})):d&&!d.nodeType?b?(b.exports=t)._=t:d._=t:e._=t})(this);